<a href="https://colab.research.google.com/github/vmahawar/tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, I am going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself!

# Introduction to [Tensors](https://www.tensorflow.org/)

In [ ]:
# Create timestamp
import datetime

print(f"Notebook last run (end-to-end): {datetime.datetime.now()}")

Notebook last run (end-to-end): 2024-08-21 20:36:31.109411


In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                     [7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix

another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype = tf.float16) # specify the data type with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# How about a tensor? (more than 2 dimensions, although, all of the above items are also technically tensors)
tensor = tf.constant([[[1,2,3],
                        [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                       [[13,14,15],
                        [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

## What is created so far:

 * Scalar: a single number
 * Vector: a number with direction (e.g. wind speed and direction)
 * Matrix: a 2-dimensional array of numbers
 * Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

In [ ]:
# Create the same tensor with tf.variable and tf.constant()
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Lets try change one of the lements in our changeable tensors
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# Lets try change one of the lements in our changeable tensors
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Let's try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

🔑**Note:** Rarely in practice will we need to decide whether to use `tf.constant` or `tf.variable` to create tensors, as tensorflow does it for us. However, if in doubt, use tf.constant and change it later if needed

In [ ]:
# Creating two random (but the same) tensors

random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
# Create two random (and different) tensors
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

# Check the tensors and see if they are equal
random_3, random_4, random_1 == random_3, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data)
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim

2

In [ ]:
# Shuffle in the same order every time using the seed parameter (won't acutally be the same)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Shuffle in the same order every time

# Set the global random seed
tf.random.set_seed(42)

# Set the operation random seed
tf.random.shuffle(value=not_shuffled,seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# Set the global random seed
tf.random.set_seed(42) # if you comment this out you'll get different results

# Set the operation random seed
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

🛠 **Exercise**: Read through TensorFlow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practise writing 5 random tensors

it looks like if we want our shuffled tensors to be in the same order, we'have got to use the global level random seed.

In [ ]:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.68789124], shape=(1,), dtype=float32)
tf.Tensor([0.7413678], shape=(1,), dtype=float32)


In [ ]:
print(tf.random.uniform([1]))  # generates 'A3'
print(tf.random.uniform([1]))  # generates 'A4'

tf.Tensor([0.7402308], shape=(1,), dtype=float32)
tf.Tensor([0.803156], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

print(f())  # prints '(A1, A2)'
print(g())  # prints '(A1, A2)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)


In [ ]:
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


# Other ways to make tensors

In [ ]:
# Create a tensors of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors

The main difference between Numpy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [ ]:
# You can also turn Numpy arrays into tensors

import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a Numpy array between 1 and 25
numpy_A

# X - tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
A = tf.constant(numpy_A, shape=(3,8))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
2 * 3 * 4

24

In [ ]:
3 * 8

24

# Getting more information from tensors

* Shape
* Rank
* Axis or Dimension
* Size

In [ ]:
# Create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
2 * 3 * 4 * 5

120

In [ ]:
# Get various attributes of our tensors
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


# Indexing Tensors

Tensors can be indexed just like lists in python

In [ ]:
# Get the dimension from each index except for the final one
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [ ]:
rank_4_tensor[:1,:,:1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [4]:
import tensorflow as tf
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [5]:
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [6]:
# Get the last item of each of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [7]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [8]:
# Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [9]:
# Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis=0) # "0" means expand in front

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [10]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

# Manipulating Tensors (Tensor Operations)

** Basic Operations **

`+`, `-`,`*`,`/`

In [11]:
# YOu can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [13]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [15]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [16]:
# Subtraction if you want
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [17]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

## **Matrix Multiplication**

In Machine Learning Matrix Learning is the most basic operation

https://www.mathsisfun.com/algebra/matrix-multiplying.html

http://matrixmultiplication.xyz/

In [19]:
# Matrix Multiplication in Tensorflow
print(tensor)
tf.matmul(tensor, tensor)


tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [20]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [22]:
# Matrix Mutlication with python operator "@"
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [24]:
# try out a different example
tensor1 = tf.constant([[1,2,5],
                      [7,2,1],
                      [3,3,3]])
tensor2 = tf.constant([[3,5],
                      [6,7],
                      [1,8]])
tf.matmul(tensor1,tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [26]:
tensor1.shape

TensorShape([3, 3])

In [27]:
tensor2.shape

TensorShape([3, 2])

In [25]:
# Using python operation @

tensor1 @ tensor2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

## 🛠 Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [58]:
tensor1 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)

In [64]:
tensor1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.46534383, 0.14094782, 0.9572284 , ..., 0.15350008, 0.41463447,
        0.3603413 ],
       [0.5787257 , 0.82150555, 0.6737056 , ..., 0.2641399 , 0.09589946,
        0.22613299],
       [0.9982258 , 0.93280184, 0.38423944, ..., 0.0608182 , 0.4924376 ,
        0.9774257 ],
       [0.32395577, 0.25026143, 0.6628783 , ..., 0.78991127, 0.32846367,
        0.5880183 ],
       [0.5977572 , 0.26534796, 0.18649602, ..., 0.7420039 , 0.5621674 ,
        0.07687378]], dtype=float32)>

In [66]:
tensor2 = tf.random.uniform(shape=[5, 300], minval=0, maxval=1)

In [67]:
tensor2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.6080158 , 0.1552211 , 0.09988916, ..., 0.33046508, 0.69261193,
        0.6339328 ],
       [0.9636282 , 0.16024065, 0.05099142, ..., 0.6139568 , 0.21535718,
        0.2679701 ],
       [0.15558493, 0.8130878 , 0.31600285, ..., 0.53727865, 0.58612597,
        0.12630022],
       [0.4472363 , 0.59625006, 0.7160723 , ..., 0.13406897, 0.44834304,
        0.5362768 ],
       [0.46803725, 0.5295124 , 0.42965698, ..., 0.76599276, 0.512838  ,
        0.8641262 ]], dtype=float32)>

In [74]:
tensor2=tf.transpose(tensor2)

In [75]:
tensor2.shape

TensorShape([300, 5])

In [76]:
tensor1 @ tensor2

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.89124 , 74.468285, 70.51692 , 74.99363 , 68.39015 ],
       [73.1517  , 75.90179 , 73.7629  , 71.94569 , 73.058945],
       [76.17784 , 78.746864, 78.08838 , 79.3074  , 72.91912 ],
       [69.007416, 70.6749  , 68.34386 , 70.94874 , 71.31838 ],
       [72.33279 , 72.694336, 71.84979 , 72.37701 , 70.06849 ]],
      dtype=float32)>

In [99]:
tf.tensordot(tensor1,tensor2,axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.89124 , 74.468285, 70.51692 , 74.99363 , 68.39015 ],
       [73.1517  , 75.90179 , 73.7629  , 71.94569 , 73.058945],
       [76.17784 , 78.746864, 78.08838 , 79.3074  , 72.91912 ],
       [69.007416, 70.6749  , 68.34386 , 70.94874 , 71.31838 ],
       [72.33279 , 72.694336, 71.84979 , 72.37701 , 70.06849 ]],
      dtype=float32)>

In [77]:
tf.matmul(tensor1,tensor2)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.89124 , 74.468285, 70.51692 , 74.99363 , 68.39015 ],
       [73.1517  , 75.90179 , 73.7629  , 71.94569 , 73.058945],
       [76.17784 , 78.746864, 78.08838 , 79.3074  , 72.91912 ],
       [69.007416, 70.6749  , 68.34386 , 70.94874 , 71.31838 ],
       [72.33279 , 72.694336, 71.84979 , 72.37701 , 70.06849 ]],
      dtype=float32)>

In [78]:
tensor_3dim = tf.random.uniform(shape=[224, 224, 3], minval=0, maxval=1)
tensor_3dim

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.5625652 , 0.8110266 , 0.89364314],
        [0.57655656, 0.82369566, 0.2332238 ],
        [0.23325253, 0.878258  , 0.07465017],
        ...,
        [0.5118426 , 0.21007383, 0.4712497 ],
        [0.8341689 , 0.63463426, 0.50980926],
        [0.7183778 , 0.14861834, 0.20190954]],

       [[0.92411923, 0.15174139, 0.8564682 ],
        [0.9724257 , 0.45743585, 0.3512149 ],
        [0.06032062, 0.32627583, 0.90619624],
        ...,
        [0.16654348, 0.445992  , 0.45741653],
        [0.45192623, 0.4234475 , 0.22283101],
        [0.33362472, 0.75051737, 0.14858723]],

       [[0.2213999 , 0.22631085, 0.86682975],
        [0.9201659 , 0.71482015, 0.528352  ],
        [0.7364427 , 0.93448055, 0.69036734],
        ...,
        [0.22012246, 0.59755397, 0.15743959],
        [0.00818264, 0.37571537, 0.12779391],
        [0.19060576, 0.43731654, 0.91006494]],

       ...,

       [[0.083022  , 0.49578834, 0.06537032],
        [0.69

In [80]:
tf.reduce_min(tensor_3dim)

<tf.Tensor: shape=(), dtype=float32, numpy=1.3113022e-06>

In [81]:
tf.reduce_max(tensor_3dim)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999839>

In [82]:
tensor_4dim = tf.random.uniform(shape=[1, 224, 224, 3], minval=0, maxval=1)
tensor_4dim

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[0.4826082 , 0.54192233, 0.39170742],
         [0.33821893, 0.714162  , 0.83715117],
         [0.8897449 , 0.13590908, 0.77442884],
         ...,
         [0.8028666 , 0.11988878, 0.7182691 ],
         [0.17086196, 0.77955055, 0.08576965],
         [0.69420266, 0.9713012 , 0.79078734]],

        [[0.52770424, 0.3794968 , 0.0352788 ],
         [0.08516574, 0.8415406 , 0.7275226 ],
         [0.450431  , 0.18005037, 0.6199248 ],
         ...,
         [0.7624786 , 0.9219421 , 0.5734676 ],
         [0.3122009 , 0.13971686, 0.5631106 ],
         [0.939088  , 0.3883965 , 0.8236563 ]],

        [[0.13820124, 0.71945024, 0.11655128],
         [0.5656539 , 0.70356476, 0.16767216],
         [0.40628827, 0.2653438 , 0.6300045 ],
         ...,
         [0.6881591 , 0.23695815, 0.86257386],
         [0.404261  , 0.48247254, 0.32898796],
         [0.7227098 , 0.490569  , 0.19999075]],

        ...,

        [[0.87089014, 0.36357915, 

In [83]:
tensor_4dim.shape

TensorShape([1, 224, 224, 3])

In [107]:
tensor_3dim = tf.squeeze(tensor_4dim)
tensor_3dim

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.4826082 , 0.54192233, 0.39170742],
        [0.33821893, 0.714162  , 0.83715117],
        [0.8897449 , 0.13590908, 0.77442884],
        ...,
        [0.8028666 , 0.11988878, 0.7182691 ],
        [0.17086196, 0.77955055, 0.08576965],
        [0.69420266, 0.9713012 , 0.79078734]],

       [[0.52770424, 0.3794968 , 0.0352788 ],
        [0.08516574, 0.8415406 , 0.7275226 ],
        [0.450431  , 0.18005037, 0.6199248 ],
        ...,
        [0.7624786 , 0.9219421 , 0.5734676 ],
        [0.3122009 , 0.13971686, 0.5631106 ],
        [0.939088  , 0.3883965 , 0.8236563 ]],

       [[0.13820124, 0.71945024, 0.11655128],
        [0.5656539 , 0.70356476, 0.16767216],
        [0.40628827, 0.2653438 , 0.6300045 ],
        ...,
        [0.6881591 , 0.23695815, 0.86257386],
        [0.404261  , 0.48247254, 0.32898796],
        [0.7227098 , 0.490569  , 0.19999075]],

       ...,

       [[0.87089014, 0.36357915, 0.98845875],
        [0.74

In [86]:
tensor_3dim = tf.reshape(tensor_4dim,shape=(224,224,3))
tensor_3dim

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.4826082 , 0.54192233, 0.39170742],
        [0.33821893, 0.714162  , 0.83715117],
        [0.8897449 , 0.13590908, 0.77442884],
        ...,
        [0.8028666 , 0.11988878, 0.7182691 ],
        [0.17086196, 0.77955055, 0.08576965],
        [0.69420266, 0.9713012 , 0.79078734]],

       [[0.52770424, 0.3794968 , 0.0352788 ],
        [0.08516574, 0.8415406 , 0.7275226 ],
        [0.450431  , 0.18005037, 0.6199248 ],
        ...,
        [0.7624786 , 0.9219421 , 0.5734676 ],
        [0.3122009 , 0.13971686, 0.5631106 ],
        [0.939088  , 0.3883965 , 0.8236563 ]],

       [[0.13820124, 0.71945024, 0.11655128],
        [0.5656539 , 0.70356476, 0.16767216],
        [0.40628827, 0.2653438 , 0.6300045 ],
        ...,
        [0.6881591 , 0.23695815, 0.86257386],
        [0.404261  , 0.48247254, 0.32898796],
        [0.7227098 , 0.490569  , 0.19999075]],

       ...,

       [[0.87089014, 0.36357915, 0.98845875],
        [0.74

In [91]:
tensor_10 = tf.constant([10,11,12,13,44,5,6,7,8,9])
tensor_10

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([10, 11, 12, 13, 44,  5,  6,  7,  8,  9], dtype=int32)>

In [92]:
tf.reduce_max(tensor_10)

<tf.Tensor: shape=(), dtype=int32, numpy=44>

In [93]:
max_index = tf.argmax(tensor_10)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [98]:
tf.one_hot(tensor_10,depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [100]:
tensor1 = tf.constant([[10,7],[3,4]])
tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [101]:
tensor1 = tf.constant([[10,7],[3,4]],dtype='int16')
tensor1

<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int16)>

In [102]:
tensor1 = tf.constant([[10,7],[3,4]],dtype='float16')
tensor1

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  4.]], dtype=float16)>

In [103]:
tensor1 = tf.constant([[10,7],[3,4]])
tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [104]:
tensor1 = tf.cast(tensor1,dtype='float16')
tensor1

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  4.]], dtype=float16)>

In [105]:
tensor1 = tf.constant([[10,7],[3,4]])
tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [106]:
tensor1 = tf.cast(tensor1,dtype=tf.float32)
tensor1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  4.]], dtype=float32)>

In [110]:
some_list = [0,1,2,3]

# one hot encode our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [111]:
some_list = [0,1,2,3]

# one hot encode our list of indices
tf.one_hot(some_list,depth=4,on_value='Y',off_value='N')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Y', b'N', b'N', b'N'],
       [b'N', b'Y', b'N', b'N'],
       [b'N', b'N', b'Y', b'N'],
       [b'N', b'N', b'N', b'Y']], dtype=object)>

In [113]:
some_list = [0,1,2,3]

# one hot encode our list of indices
tf.one_hot(some_list,depth=4,on_value='O',off_value='X')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'O', b'X', b'X', b'X'],
       [b'X', b'O', b'X', b'X'],
       [b'X', b'X', b'O', b'X'],
       [b'X', b'X', b'X', b'O']], dtype=object)>

In [114]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [116]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [117]:
tf.math.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [118]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>